(() => {
  'use strict';
  const KEY='we-world-events-v1';
  let map=null, marker=null, circle=null, card=null, lastKey='', lastEvent=null, timer=null;
  const $=s=>document.querySelector(s);
  const hav=(a,b)=>{const R=6371000,p=Math.PI/180,d1=(b.lat-a.lat)*p,d2=(b.lng-a.lng)*p,x=Math.sin(d1/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,x)));};
  function weather(){const t=$('#wx')?.textContent||''; if(/storm|⛈/i.test(t))return'storm'; if(/rain|🌧|drizzle|🌦/i.test(t))return'rain'; if(/snow|❄/i.test(t))return'snow'; if(/cloud|☁/i.test(t))return'cloud'; return'clear';}
  function eventFor(){const h=new Date().getHours(),w=weather(); if(w==='storm')return{type:'STORM FRONT',icon:'⛈️',text:'The sky is charged. Rare signals are awakening.',cls:'storm'}; if(w==='rain')return{type:'RAIN ECHO',icon:'🌧️',text:'Rain is reshaping the Explorer field around you.',cls:'rain'}; if(w==='snow')return{type:'FROST SIGNAL',icon:'❄️',text:'Cold air detected. Something unusual is nearby.',cls:'snow'}; if(h>=20||h<6)return{type:'NIGHT SIGNAL',icon:'🌙',text:'The world gets stranger after dark. Keep exploring.',cls:'night'}; if(h>=17&&h<20)return{type:'GOLDEN HOUR',icon:'🌅',text:'Light is changing. Rare discoveries have surfaced.',cls:'gold'}; return{type:'LIVING WORLD',icon:'✨',text:'Move through the map. The world is generating around you.',cls:'day'};}
  function styles(){if($('#we-event-style'))return;const s=document.createElement('style');s.id='we-event-style';s.textContent=`.we-event-card{position:fixed;z-index:6400;left:50%;top:88px;transform:translateX(-50%) translateY(-12px) scale(.97);width:min(430px,calc(100vw - 110px));padding:11px 14px;border:1px solid rgba(105,225,255,.34);border-radius:18px;background:rgba(5,17,25,.88);backdrop-filter:blur(18px);box-shadow:0 12px 45px rgba(0,0,0,.25),0 0 30px rgba(50,205,255,.12);color:#effcff;opacity:0;transition:.45s cubic-bezier(.2,.8,.2,1);pointer-events:none;font:600 11px/1.35 system-ui,sans-serif}.we-event-card.show{opacity:1;transform:translateX(-50%) translateY(0) scale(1)}.we-event-card .row{display:flex;align-items:center;gap:10px}.we-event-card .icon{font-size:25px;filter:drop-shadow(0 0 9px rgba(100,230,255,.6))}.we-event-card b{display:block;letter-spacing:.14em;font-size:10px;color:#7ee9ff}.we-event-card small{display:block;margin-top:2px;color:#b9cbd2;font-size:11px}.we-event-ring{animation:weRing 2.2s ease-out infinite}@keyframes weRing{0%{opacity:.65;transform:scale(.75)}70%{opacity:.08;transform:scale(1.25)}100%{opacity:0;transform:scale(1.4)}}@media(max-width:520px){.we-event-card{top:80px;width:calc(100vw - 96px)}}`;
    document.head.appendChild(s);
  }
  function ui(){if(card)return;card=document.createElement('div');card.className='we-event-card';document.body.appendChild(card);}
  function show(e){lastEvent=e;if(!card)return;card.innerHTML='<div class="row"><span class="icon">'+e.icon+'</span><div><b>'+e.type+'</b><small>'+e.text+'</small></div></div>';card.classList.add('show');clearTimeout(show.t);show.t=setTimeout(()=>card.classList.remove('show'),5200);}
  function attach(){map=window.__WORLD_EXPLORER_MAP__; if(!map)return false; if(!circle){circle=L.circle(map.getCenter(),{radius:95,color:'#64e8ff',weight:2,opacity:.25,fillColor:'#39d9ff',fillOpacity:.035,interactive:false,className:'we-event-ring'}).addTo(map);} if(!marker){marker=L.circleMarker(map.getCenter(),{radius:5,color:'#d9fbff',weight:2,fillColor:'#5ce6ff',fillOpacity:1,interactive:false}).addTo(map);} return true;}
  function tick(){if(!attach())return;const c=map.getCenter(),e=eventFor();circle.setLatLng(c);marker.setLatLng(c);const key=[e.type,c.lat.toFixed(2),c.lng.toFixed(2)].join(':');if(key!==lastKey){lastKey=key;show(e);try{localStorage.setItem(KEY,JSON.stringify({event:e.type,at:Date.now(),lat:c.lat,lng:c.lng}));}catch(_){}}}
  function boot(){styles();ui();if(!timer)timer=setInterval(tick,3500);tick();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,700),{once:true});else setTimeout(boot,700);
})();